# -*- coding: utf-8 -*-
"""Canonical Battle IR model.

This package contains only semantic IR structures and value representations.
Provenance (game version, method index, native RVA) is stored separately from
runtime semantics and must never participate in sandbox execution logic.
The source of truth for recovered primitives is the explicit semantic
artifact catalog, loaded and validated by ``catalog.py`` /
``semantic_artifact.py`` / ``semantic_batch.py``.
"""
from __future__ import annotations

from hsr_battle_agent.battle_ir.catalog import (
    CATALOG_SCHEMA,
    CatalogArtifactEntry,
    SemanticCatalog,
    default_catalog_path,
    load_catalog_primitives,
    load_semantic_catalog,
    validate_semantic_catalog,
)
from hsr_battle_agent.battle_ir.model import (
    DYNAMIC_VALUE_EQUALS_PRIMITIVE_ID,
    DYNAMIC_VALUE_IS_ARRAY_PRIMITIVE_ID,
    DYNAMIC_VALUE_IS_MAP_PRIMITIVE_ID,
    DYNAMIC_VALUE_IS_NULL_PRIMITIVE_ID,
    DYNAMIC_VALUE_STRING_PRIMITIVE_ID,
    DYNAMIC_VALUE_TO_BOOL_PRIMITIVE_ID,
    DYNAMIC_VALUE_TO_DOUBLE_PRIMITIVE_ID,
    DYNAMIC_VALUE_TO_FLOAT_PRIMITIVE_ID,
    DYNAMIC_VALUE_TO_INT_PRIMITIVE_ID,
    DYNAMIC_VALUE_TO_LONG_PRIMITIVE_ID,
    DYNAMIC_VALUE_TO_UINT_PRIMITIVE_ID,
    DYNAMIC_VALUE_TYPE_PRIMITIVE_ID,
    EVALUATOR_SPEC_FIXPOINT_EQUAL_INT32_PRIMITIVE_ID,
    EVALUATOR_SPEC_FIXPOINT_EQUAL_RAW_PRIMITIVE_ID,
    EVALUATOR_SPEC_FIXPOINT_NOT_EQUAL_RAW_PRIMITIVE_ID,
    EVALUATOR_SPEC_FROM_FIXPOINT_RAW_PRIMITIVE_ID,
    EVALUATOR_SPEC_FROM_INT32_PRIMITIVE_ID,
    FIXPOINT_EQUAL_PRIMITIVE_ID,
    FIXPOINT_FROM_INT32_PRIMITIVE_ID,
    FIXPOINT_GREATER_EQUAL_PRIMITIVE_ID,
    FIXPOINT_GREATER_PRIMITIVE_ID,
    FIXPOINT_IS_NEGATIVE_PRIMITIVE_ID,
    FIXPOINT_IS_POSITIVE_PRIMITIVE_ID,
    FIXPOINT_IS_ZERO_PRIMITIVE_ID,
    FIXPOINT_LESS_EQUAL_PRIMITIVE_ID,
    FIXPOINT_LESS_PRIMITIVE_ID,
    FIXPOINT_NOT_EQUAL_PRIMITIVE_ID,
    ENTITY_GAME_ENTITY_RUNTIME_ID_PRIMITIVE_ID,
    TARGET_COLLAPSE_REQUIRED_SINGLE_OR_NULL_PRIMITIVE_ID,
    TARGET_COLLAPSE_SINGLE_OR_NULL_PRIMITIVE_ID,
    TARGET_CONTEXT_OWNER_ENTITY_PRIMITIVE_ID,
    TARGET_CONTEXT_TASK_ACTION_TARGET_PRIMITIVE_ID,
    TARGET_SELECT_CASTER_PRIMITIVE_ID,
    TARGET_SELECT_NONE_PRIMITIVE_ID,
    TARGET_SELECT_TASK_ACTION_TARGET_PRIMITIVE_ID,
    TASK_BEGIN_IMMEDIATE_SUCCESS_PRIMITIVE_ID,
    TASK_BEGIN_SELECT_SINGLE_TARGET_PRIMITIVE_ID,
    TASK_EXECUTOR_BASE_READY_INIT_PRIMITIVE_ID,
    TASK_EXECUTOR_INIT_PRIMITIVE_ID,
    TASK_RESET_READY_CLEAR_SELECTED_TARGET_PRIMITIVE_ID,
    TASK_RESET_READY_PRIMITIVE_ID,
    TASK_STATE_READ_PRIMITIVE_ID,
    PrimitiveArgument,
    PrimitiveCall,
    PrimitiveInputSpec,
    PrimitiveResult,
    PrimitiveSpec,
)
from hsr_battle_agent.battle_ir.provenance import SourceProvenance
from hsr_battle_agent.battle_ir.semantic_artifact import (
    RecoveredPrimitive,
    SemanticArtifactError,
    default_artifact_path,
    load_vertical_slice_01,
)
from hsr_battle_agent.battle_ir.semantic_batch import (
    BATCH_SCHEMA,
    default_batch_02_path,
    load_battle_semantics_batch,
    load_dynamic_value_batch_02,
    validate_battle_semantics_batch,
    validate_dynamic_value_batch_02,
)
from hsr_battle_agent.battle_ir.values import (
    DynamicValue,
    DynamicValueType,
    EvaluatorSpec,
    ObjectRef,
)
from hsr_battle_agent.battle_ir.actions import TaskExecutionState, TaskState
from hsr_battle_agent.battle_ir.targets import EntityRef, TargetSet

__all__ = [
    "BATCH_SCHEMA",
    "CATALOG_SCHEMA",
    "DYNAMIC_VALUE_EQUALS_PRIMITIVE_ID",
    "DYNAMIC_VALUE_IS_ARRAY_PRIMITIVE_ID",
    "DYNAMIC_VALUE_IS_MAP_PRIMITIVE_ID",
    "DYNAMIC_VALUE_IS_NULL_PRIMITIVE_ID",
    "DYNAMIC_VALUE_STRING_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TO_BOOL_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TO_DOUBLE_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TO_FLOAT_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TO_INT_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TO_LONG_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TO_UINT_PRIMITIVE_ID",
    "DYNAMIC_VALUE_TYPE_PRIMITIVE_ID",
    "EVALUATOR_SPEC_FIXPOINT_EQUAL_INT32_PRIMITIVE_ID",
    "EVALUATOR_SPEC_FIXPOINT_EQUAL_RAW_PRIMITIVE_ID",
    "EVALUATOR_SPEC_FIXPOINT_NOT_EQUAL_RAW_PRIMITIVE_ID",
    "EVALUATOR_SPEC_FROM_FIXPOINT_RAW_PRIMITIVE_ID",
    "EVALUATOR_SPEC_FROM_INT32_PRIMITIVE_ID",
    "ENTITY_GAME_ENTITY_RUNTIME_ID_PRIMITIVE_ID",
    "FIXPOINT_EQUAL_PRIMITIVE_ID",
    "FIXPOINT_FROM_INT32_PRIMITIVE_ID",
    "FIXPOINT_GREATER_EQUAL_PRIMITIVE_ID",
    "FIXPOINT_GREATER_PRIMITIVE_ID",
    "FIXPOINT_IS_NEGATIVE_PRIMITIVE_ID",
    "FIXPOINT_IS_POSITIVE_PRIMITIVE_ID",
    "FIXPOINT_IS_ZERO_PRIMITIVE_ID",
    "FIXPOINT_LESS_EQUAL_PRIMITIVE_ID",
    "FIXPOINT_LESS_PRIMITIVE_ID",
    "FIXPOINT_NOT_EQUAL_PRIMITIVE_ID",
    "TARGET_COLLAPSE_REQUIRED_SINGLE_OR_NULL_PRIMITIVE_ID",
    "TARGET_COLLAPSE_SINGLE_OR_NULL_PRIMITIVE_ID",
    "TARGET_CONTEXT_OWNER_ENTITY_PRIMITIVE_ID",
    "TARGET_CONTEXT_TASK_ACTION_TARGET_PRIMITIVE_ID",
    "TARGET_SELECT_CASTER_PRIMITIVE_ID",
    "TARGET_SELECT_NONE_PRIMITIVE_ID",
    "TARGET_SELECT_TASK_ACTION_TARGET_PRIMITIVE_ID",
    "TASK_BEGIN_IMMEDIATE_SUCCESS_PRIMITIVE_ID",
    "TASK_BEGIN_SELECT_SINGLE_TARGET_PRIMITIVE_ID",
    "TASK_EXECUTOR_BASE_READY_INIT_PRIMITIVE_ID",
    "TASK_EXECUTOR_INIT_PRIMITIVE_ID",
    "TASK_RESET_READY_CLEAR_SELECTED_TARGET_PRIMITIVE_ID",
    "TASK_RESET_READY_PRIMITIVE_ID",
    "TASK_STATE_READ_PRIMITIVE_ID",
    "CatalogArtifactEntry",
    "DynamicValue",
    "DynamicValueType",
    "EntityRef",
    "EvaluatorSpec",
    "ObjectRef",
    "TargetSet",
    "TaskExecutionState",
    "TaskState",
    "PrimitiveArgument",
    "PrimitiveCall",
    "PrimitiveInputSpec",
    "PrimitiveResult",
    "PrimitiveSpec",
    "RecoveredPrimitive",
    "SemanticArtifactError",
    "SemanticCatalog",
    "SourceProvenance",
    "default_artifact_path",
    "default_batch_02_path",
    "default_catalog_path",
    "load_battle_semantics_batch",
    "load_catalog_primitives",
    "load_dynamic_value_batch_02",
    "load_semantic_catalog",
    "load_vertical_slice_01",
    "validate_battle_semantics_batch",
    "validate_dynamic_value_batch_02",
    "validate_semantic_catalog",
]
