#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the first E2E simple-skill candidate index."""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "data" / "raw" / "4.4.54" / "simple_skill_candidate_index_21.json"

DATA = {
    "schema": "simple_skill_candidate_index/1",
    "game_version": "4.4.54",
    "status": "CONTENT_TOPOLOGY_SELECTION",
    "candidate_count_scanned": 10,
    "character_mapping_note": "The repository contains ability-path indexes but not parsed ability JSON contents; character-to-config links below are representative from known ability paths and are marked SUPPORTED_BY_ABILITY_PATH, not CONFIRMED_BY_CONFIG_CONTENT.",
    "ranked_candidates": [
        {
            "rank": 1,
            "skill": "HealHP config-level candidate (representative healer skill path: Avatar_Natasha_00_Ability.json / Avatar_Lynx_00_Ability.json / Avatar_Bailu_00_Ability.json)",
            "character_identifier": "Natasha / Lynx / Bailu (representative paths)",
            "skill_identifier": "HealHP",
            "design_data_source": "data/extracted/4.4.53/direct_json/TurnBasedAbilityConfig.json",
            "root_ability_or_task_config": "RPG.GameCore.HealHP",
            "generated_executor_chain": "AAOLFLMHBEK (M507657 OnTaskBegin) -> M507658 -> M506500 DirectChangeHP -> M506499 DirectDamageHP",
            "target_config": "Target selector supported by existing target bridge",
            "damage_producing_config_or_executor": "HealHP / DirectChangeHP",
            "pgoo_appears": False,
            "reaches_pgoo_blocker": False,
            "damage_path_class": "C.USES_DIRECT_HP_OR_ALREADY_RECOVERED_PATH",
            "supported_primitives": ["DynamicValue", "FixPoint", "Target", "DirectChangeHP", "DirectDamageHP mode 0", "HP Runtime"],
            "unknown_primitives": ["exact HealHP config field mapping in a specific character ability file"],
            "blocker_count": 1,
        },
        {
            "rank": 2,
            "skill": "LoseHP config-level candidate (representative simple HP-loss skill path)",
            "character_identifier": "Representative avatar/enemy path using LoseHP",
            "skill_identifier": "LoseHP",
            "design_data_source": "action_config_runtime_bridge_06.json",
            "root_ability_or_task_config": "RPG.GameCore.LoseHP",
            "generated_executor_chain": "PMIOBHFIGCA (M507899 OnTaskBegin) -> M504579 TargetDamageHP -> M506499 DirectDamageHP",
            "target_config": "Target selector supported",
            "damage_producing_config_or_executor": "LoseHP / TargetDamageHP",
            "pgoo_appears": False,
            "reaches_pgoo_blocker": False,
            "damage_path_class": "C.USES_DIRECT_HP_OR_ALREADY_RECOVERED_PATH",
            "supported_primitives": ["DynamicValue", "FixPoint", "Target", "TargetDamageHP", "DirectDamageHP mode 0", "HP Runtime"],
            "unknown_primitives": ["exact real character skill using LoseHP in available DesignData"],
            "blocker_count": 1,
        },
        {
            "rank": 3,
            "skill": "LoseHPByRatio config-level candidate",
            "character_identifier": "Representative avatar/enemy path using LoseHPByRatio",
            "skill_identifier": "LoseHPByRatio",
            "design_data_source": "action_config_runtime_bridge_06.json",
            "root_ability_or_task_config": "RPG.GameCore.LoseHPByRatio",
            "generated_executor_chain": "FNJBHDJHIIG (M507897 OnTaskBegin) -> M504579 TargetDamageHP -> M506499 DirectDamageHP",
            "target_config": "Target selector supported",
            "damage_producing_config_or_executor": "LoseHPByRatio / TargetDamageHP",
            "pgoo_appears": False,
            "reaches_pgoo_blocker": False,
            "damage_path_class": "C.USES_DIRECT_HP_OR_ALREADY_RECOVERED_PATH",
            "supported_primitives": ["DynamicValue", "FixPoint", "Target", "TargetDamageHP", "DirectDamageHP mode 0", "HP Runtime"],
            "unknown_primitives": ["exact real character skill using LoseHPByRatio"],
            "blocker_count": 1,
        },
        {
            "rank": 4,
            "skill": "SetHP config-level candidate (representative direct HP set skill)",
            "character_identifier": "Representative path using SetHP",
            "skill_identifier": "SetHP",
            "design_data_source": "action_config_runtime_bridge_06.json / Handoff 12",
            "root_ability_or_task_config": "RPG.GameCore.SetHP",
            "generated_executor_chain": "ONECLKJPNJP (M508871 OnTaskBegin) -> M506500 DirectChangeHP -> M506499 DirectDamageHP",
            "target_config": "Target selector supported",
            "damage_producing_config_or_executor": "SetHP / DirectChangeHP",
            "pgoo_appears": False,
            "reaches_pgoo_blocker": False,
            "damage_path_class": "C.USES_DIRECT_HP_OR_ALREADY_RECOVERED_PATH",
            "supported_primitives": ["DynamicValue", "FixPoint", "Target", "DirectChangeHP", "DirectDamageHP mode 0", "HP Runtime"],
            "unknown_primitives": ["exact real character skill using SetHP"],
            "blocker_count": 1,
        },
        {
            "rank": 5,
            "skill": "Asta Basic ATK / simple skill (representative avatar damage path)",
            "character_identifier": "Asta",
            "skill_identifier": "Basic ATK / simple damage skill",
            "design_data_source": "data/extracted/4.4.53/direct_json/TurnBasedAbilityConfig.json (Avatar_Asta_00_Ability.json)",
            "root_ability_or_task_config": "UNKNOWN until ability JSON content is parsed; likely DamageByAttackProperty family",
            "generated_executor_chain": "UNKNOWN -> PGOOHIHKHNJ -> M507296 -> M507304 -> runtime dispatch -> M507308",
            "target_config": "UNKNOWN",
            "damage_producing_config_or_executor": "likely DamageByAttackProperty",
            "pgoo_appears": True,
            "reaches_pgoo_blocker": True,
            "damage_path_class": "A.USES_BLOCKED_PGOO_DAMAGEBYATTACKPROPERTY",
            "supported_primitives": ["Target", "FixPoint", "DirectDamageHP mode 0"],
            "unknown_primitives": ["PGOOHIHKHNJ +0x120 dispatch target", "B[+0x2D8] producer"],
            "blocker_count": 3,
        },
        {
            "rank": 6,
            "skill": "Herta Basic ATK / simple skill",
            "character_identifier": "Herta",
            "skill_identifier": "Basic ATK / simple damage skill",
            "design_data_source": "TurnBasedAbilityConfig.json (Avatar_Herta_00_Ability.json)",
            "root_ability_or_task_config": "UNKNOWN; likely DamageByAttackProperty family",
            "generated_executor_chain": "UNKNOWN -> PGOOHIHKHNJ -> M507296 -> M507304 -> runtime dispatch -> M507308",
            "target_config": "UNKNOWN",
            "damage_producing_config_or_executor": "likely DamageByAttackProperty",
            "pgoo_appears": True,
            "reaches_pgoo_blocker": True,
            "damage_path_class": "A.USES_BLOCKED_PGOO_DAMAGEBYATTACKPROPERTY",
            "supported_primitives": ["Target", "FixPoint", "DirectDamageHP mode 0"],
            "unknown_primitives": ["PGOOHIHKHNJ +0x120 dispatch target", "B[+0x2D8] producer"],
            "blocker_count": 3,
        },
        {
            "rank": 7,
            "skill": "Dan Heng Basic ATK / simple skill",
            "character_identifier": "Dan Heng",
            "skill_identifier": "Basic ATK / simple damage skill",
            "design_data_source": "TurnBasedAbilityConfig.json (Avatar_DanHeng_00_Ability.json)",
            "root_ability_or_task_config": "UNKNOWN; likely DamageByAttackProperty family",
            "generated_executor_chain": "UNKNOWN -> PGOOHIHKHNJ -> M507296 -> M507304 -> runtime dispatch -> M507308",
            "target_config": "UNKNOWN",
            "damage_producing_config_or_executor": "likely DamageByAttackProperty",
            "pgoo_appears": True,
            "reaches_pgoo_blocker": True,
            "damage_path_class": "A.USES_BLOCKED_PGOO_DAMAGEBYATTACKPROPERTY",
            "supported_primitives": ["Target", "FixPoint", "DirectDamageHP mode 0"],
            "unknown_primitives": ["PGOOHIHKHNJ +0x120 dispatch target", "B[+0x2D8] producer"],
            "blocker_count": 3,
        },
        {
            "rank": 8,
            "skill": "March 7th Basic ATK / simple skill",
            "character_identifier": "March 7th",
            "skill_identifier": "Basic ATK / simple damage skill",
            "design_data_source": "TurnBasedAbilityConfig.json (Avatar_Mar_7th_00_Ability.json)",
            "root_ability_or_task_config": "UNKNOWN; likely DamageByAttackProperty family",
            "generated_executor_chain": "UNKNOWN -> PGOOHIHKHNJ -> M507296 -> M507304 -> runtime dispatch -> M507308",
            "target_config": "UNKNOWN",
            "damage_producing_config_or_executor": "likely DamageByAttackProperty",
            "pgoo_appears": True,
            "reaches_pgoo_blocker": True,
            "damage_path_class": "A.USES_BLOCKED_PGOO_DAMAGEBYATTACKPROPERTY",
            "supported_primitives": ["Target", "FixPoint", "DirectDamageHP mode 0"],
            "unknown_primitives": ["PGOOHIHKHNJ +0x120 dispatch target", "B[+0x2D8] producer"],
            "blocker_count": 3,
        },
        {
            "rank": 9,
            "skill": "Trailblazer (Physical) Basic ATK / simple skill",
            "character_identifier": "Trailblazer (PlayerBoy/PlayerGirl)",
            "skill_identifier": "Basic ATK / simple damage skill",
            "design_data_source": "TurnBasedAbilityConfig.json (Avatar_PlayerBoy_00_Ability.json / Avatar_PlayerGirl_00_Ability.json)",
            "root_ability_or_task_config": "UNKNOWN; likely DamageByAttackProperty family",
            "generated_executor_chain": "UNKNOWN -> PGOOHIHKHNJ -> M507296 -> M507304 -> runtime dispatch -> M507308",
            "target_config": "UNKNOWN",
            "damage_producing_config_or_executor": "likely DamageByAttackProperty",
            "pgoo_appears": True,
            "reaches_pgoo_blocker": True,
            "damage_path_class": "A.USES_BLOCKED_PGOO_DAMAGEBYATTACKPROPERTY",
            "supported_primitives": ["Target", "FixPoint", "DirectDamageHP mode 0"],
            "unknown_primitives": ["PGOOHIHKHNJ +0x120 dispatch target", "B[+0x2D8] producer"],
            "blocker_count": 3,
        },
        {
            "rank": 10,
            "skill": "ProcessStoredDamage config-level candidate",
            "character_identifier": "Representative stored-damage executor path",
            "skill_identifier": "ProcessStoredDamage",
            "design_data_source": "action_config_runtime_bridge_06.json / topology probe 13",
            "root_ability_or_task_config": "RPG.GameCore.ProcessStoredDamage",
            "generated_executor_chain": "AABAELPKKGK (M508236 OnTaskBegin) -> M508237 -> M507308 -> M504579",
            "target_config": "Target selector supported",
            "damage_producing_config_or_executor": "ProcessStoredDamage / M507308",
            "pgoo_appears": True,
            "reaches_pgoo_blocker": True,
            "damage_path_class": "A.USES_BLOCKED_PGOO_DAMAGEBYATTACKPROPERTY",
            "supported_primitives": ["Target", "FixPoint", "TargetDamageHP", "DirectDamageHP mode 0"],
            "unknown_primitives": ["PGOOHIHKHNJ +0x120 dispatch target", "B[+0x2D8] producer"],
            "blocker_count": 3,
        },
    ],
    "recommended_primary_skill": {
        "skill": "HealHP config-level candidate",
        "character_identifier": "Natasha / Lynx / Bailu representative ability paths",
        "reason": "Uses already recovered DirectChangeHP -> DirectDamageHP mode-0 path and does not reach PGOOHIHKHNJ.",
        "remaining_semantic_frontier": "Confirm which real character ability file instantiates HealHP and recover its config field mapping.",
    },
    "pgoo_blocker_assessment": {
        "result": "BYPASSABLE_FOR_NON_DAMAGE_OR_DIRECT_HP_SLICE",
        "evidence": "HealHP/LoseHP/LoseHPByRatio/SetHP configs map to executor chains that avoid PGOOHIHKHNJ and use already recovered HP primitives.",
        "note": "Typical Basic ATK / direct damage skills are expected to use DamageByAttackProperty and therefore hit the PGOOHIHKHNJ runtime dispatch.",
    },
    "recommended_next_step": "Select a real healer skill ability path (Natasha/Lynx/Bailu) and parse its ability JSON content to confirm HealHP instantiation; then build the first E2E Sandbox slice around HealHP -> DirectChangeHP -> DirectDamageHP.",
}


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(DATA, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
